#!/bin/bash
echo "Opening all services in browser..."
echo ""
echo "1. Grafana Dashboard: http://localhost:3000"
echo "   Login: admin / admin123"
echo ""
echo "2. Prometheus: http://localhost:9090"
echo "   Try query: rate(http_requests_total[1m])"
echo ""
echo "3. Kafka UI: http://localhost:8080"
echo "   View topics and messages"
echo ""
echo "4. cAdvisor: http://localhost:8081"
echo "   View container resource usage"
echo ""
echo "5. WagonLits Metrics: http://localhost:3001/metrics"
echo "6. DevMateriels Metrics: http://localhost:3002/metrics"
echo "7. ConstructWagons Metrics: http://localhost:3003/metrics"
echo ""
echo "8. GitHub Actions: https://github.com/0Bleak/erp-interoperability-prototype/actions"
